version: 1
services:
  - type: web
    name: mangarw-v2
    env: node
    plan: free
    buildCommand: npm install && npm install --os=linux --cpu=x64 sharp
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16
